### ISSUE TITLE
failed to start istio-webhook  

### ISSUE THREAD

**Issue by yang59324** [knative/operator#519]
knative-operator version sha256@2a4add19e8ba5f59e6bb2754e828bed4eb988ad516ea118adf401a15624f22cc

knative-serving cr
```
  name: knative-serving
  namespace: knative-serving
  resourceVersion: '13680984'
  uid: 23324a02-950c-49d5-b49e-a337d3eccf3d
  selfLink: >-
    /apis/operator.knative.dev/v1alpha1/namespaces/knative-serving/knativeservings/knative-serving
spec:
  registry:
    override:
      activator: >-
        knative/activator:e93d0d34250c312fd4b856f92ab682f95e0730c70683c8308c12006fca776ae9
      autoscaler: >-
        knative/autoscaler:d1e385623fe668b0432a6bd1fbdfe5242ec5f637e94b253b73a98e4297278d54
      autoscaler-hpa: >-
      knative/autoscaler-hpa:805bbe9dcfefa942505625b3e0638bfe4275ff13e1f5858ac7de995ff6e0a1c6
      controller: >-
      knative/controller:b049234187c3a8035a6196344a2759244dc421822ac39738113e3aedf3eb8374
      istio-webhook: >-
      knative/net-istio-webhook:203acf3ac797f1e66a6ea3aa02a7060d199af521d7fbc5633ef79a05a4aec8fa
      networking-istio: >-
      knative/net-istio-controller:5555b83528d9f694268c521c78caae0a9c31c7e1c98795d854f6fe990d561312
      webhook: >-
      knative/webhook:fdf57643768d1b4337dbb347dade96cbdb2cdca74e564909f73895bf377fbadf
```
log of istio webhook pod
```
panic: failed to convert the environment variable "WEBHOOK_PORT" : strconv.Atoi: parsing "tcp://192.168.111.87:9090": invalid syntax

goroutine 1 [running]:
knative.dev/pkg/webhook.PortFromEnv(0x20fb, 0xd)
knative.dev/pkg@v0.0.0-20210215165523-84c98f3c3e7a/webhook/env.go:37 +0x1e8
main.main()
knative.dev/serving/cmd/webhook/main.go:158 +0xab
```

**Comment by houshengbo** [comment]
This is an interesting issue.
What is the value for WEBHOOK_PORT, that you set for the deployment `istio-webhook`?
`tcp://192.168.111.87:9090"`? If you change the default value for WEBHOOK_PORT, plz use an integer as valid port number.

**Comment by nak3** [comment]
This issue happens as net-istio's webhook and serving's webhook have same container name `webhook`. Please configure the registry override with `net-istio/webhook` and `webhook/webhook` like this:

```
spec:
  registry:
    override:
      webhook/webhook: >-
      knative/webhook:fdf57643768d1b4337dbb347dade96cbdb2cdca74e564909f73895bf377fbadf
      net-istio/webhook: >-
      knative/net-istio:somethingsomething-hash
```

**Comment by nak3** [comment]
/close

I think this can be closed. Please feel free to re-open it if anyone is still getting the error.
