### ISSUE TITLE
knative-operator crashes with SIGSEGV, k3s v1.21.5

### ISSUE THREAD

**Issue by PeterGrace** [knative/operator#975]
**Describe the bug**
knative-operator crashes with a segmentation fault shortly after the lease-election phase of its lifecycle

**Expected behavior**
knative-operator would not crash.

**To Reproduce**
Install knative-operator by applying the operator.yaml file.

**Knative release version**
knative-operator image `gcr.io/knative-releases/knative.dev/operator/cmd/operator@sha256:2a3d5775443ab4a49cf8d5dc89f34585aa324ac8be64285e2d3d0ff5f962ac8a`

**Additional context**

This is a k3s environment running 1.21.5+k3s2 -- I'm not sure if there's some functionality in knative that requires >=1.22?

Log snippet of crash text:
```
{"severity":"WARNING","timestamp":"2022-02-22T18:51:47.939251125Z","logger":"knative-operator","caller":"logging/warning_handler.go:32","message":"API Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget","knative.dev/pod":"knative-operator-7b8c4857bb-w6khx"}
{"severity":"INFO","timestamp":"2022-02-22T18:51:47.94041132Z","logger":"knative-operator.manifestival","caller":"manifestival@v0.7.1/manifestival.go:145","message":"Merging","knative.dev/pod":"knative-operator-7b8c4857bb-w6khx","diff":"{\"spec\":{\"selector\":{\"matchLabels\":{\"app\":\"eventing-webhook\"}}}}"}
{"severity":"INFO","timestamp":"2022-02-22T18:51:47.941195358Z","logger":"knative-operator.manifestival","caller":"manifestival@v0.7.1/manifestival.go:207","message":"Updating","knative.dev/pod":"knative-operator-7b8c4857bb-w6khx","name":"knative-eventing/eventing-webhook","type":"policy/v1beta1, Kind=PodDisruptionBudget"}
{"severity":"WARNING","timestamp":"2022-02-22T18:51:48.015769908Z","logger":"knative-operator","caller":"logging/warning_handler.go:32","message":"API Warning: policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget","knative.dev/pod":"knative-operator-7b8c4857bb-w6khx"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1162cb8]

goroutine 564 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GetKind(...)
        k8s.io/apimachinery@v0.22.5/pkg/apis/meta/v1/unstructured/unstructured.go:226
github.com/manifestival/manifestival.okToDelete(0x0)
        github.com/manifestival/manifestival@v0.7.1/manifestival.go:234 +0x38
github.com/manifestival/manifestival.Manifest.delete({{0xc0004c9000, 0x34, 0x40}, {0x1ccb2b0, 0xc000146dc0}, {{0x1cebe20, 0xc0007adb90}, 0x0}}, 0x1ccb2b0, {0x0, ...})
        github.com/manifestival/manifestival@v0.7.1/manifestival.go:179 +0xae
github.com/manifestival/manifestival.Manifest.Delete({{0xc0004c9000, 0x34, 0x40}, {0x1ccb2b0, 0xc000146dc0}, {{0x1cebe20, 0xc0007adb90}, 0x0}}, {0x0, 0x0, ...})
        github.com/manifestival/manifestival@v0.7.1/manifestival.go:116 +0x1e5
knative.dev/operator/pkg/reconciler/common.Uninstall(0xc000e7dc00)
        knative.dev/operator/pkg/reconciler/common/install.go:76 +0x278
knative.dev/operator/pkg/reconciler/knativeserving.(*Reconciler).FinalizeKind(0xc0001c00e0, {0x1ccb198, 0xc000eda690}, 0xc000ea4fc0)
        knative.dev/operator/pkg/reconciler/knativeserving/knativeserving.go:86 +0x365
knative.dev/operator/pkg/client/injection/reconciler/operator/v1alpha1/knativeserving.(*reconcilerImpl).Reconcile(0xc0004d4aa0, {0x1ccb198, 0xc000eda660}, {0xc0008013e0, 0x1f})
        knative.dev/operator/pkg/client/injection/reconciler/operator/v1alpha1/knativeserving/reconciler.go:240 +0x518
knative.dev/pkg/controller.(*Impl).processNextWorkItem(0xc0008418c0)
        knative.dev/pkg@v0.0.0-20220217155112-d48172451966/controller/controller.go:542 +0x5a5
knative.dev/pkg/controller.(*Impl).RunContext.func3()
        knative.dev/pkg@v0.0.0-20220217155112-d48172451966/controller/controller.go:478 +0x68
created by knative.dev/pkg/controller.(*Impl).RunContext
        knative.dev/pkg@v0.0.0-20220217155112-d48172451966/controller/controller.go:476 +0x2de
```

**Comment by houshengbo** [comment]
@PeterGrace Am I able to produce this issue on ANY kubernetes 1.21.5? I do not have k3s with me.

**Comment by houshengbo** [comment]
@jcrossley3 Could you check on this issue? Thx.

**Comment by PeterGrace** [comment]
> @PeterGrace Am I able to produce this issue on ANY kubernetes 1.21.5? I do not have k3s with me.
I would assume so as this looks to be a container problem rather than a kubernetes scheduling issue -- the only other interesting tidbit is the fact that k3s uses containerd instead of docker, which *might* affect things but not sure about that.

**Comment by houshengbo** [comment]
@PeterGrace Are you installing operator.yaml 1.2.0?

**Comment by PeterGrace** [comment]
> @PeterGrace Are you installing operator.yaml 1.2.0? Did u NOT apply any CR? Only installing the operator.yaml? 

I am installing via operator.yaml  release v1.2.1.  I see the operator.yaml contains CRD's.  I assume these are expected?

> If by any chance u can use 1.22 kube, does the issue disappear? Can u verify on this?

Not immediately, I'd have to coordinate a cluster upgrade for that.

**Comment by darkstarmv** [comment]
I have faced same problem after upgrade to kubernetes v1.23.4

**Comment by houshengbo** [comment]
@darkstarmv What is the knative operator version you are using?
I am using 1.23.3 Kube and install knative operator 1.2, it worked fine.

**Comment by jbalonso** [comment]
I am seeing the same stacktrace with operator `1.3.0` (specifically: `gcr.io/knative-releases/knative.dev/operator/cmd/operator@sha256:a1bb612a75386c491b3739a2bf3c04a8e1f6710548e780941f8fe08b912905ae`) running on an RPi4 cluster on Talos 1.0 with k8s `v1.23.5`.

**Comment by jbalonso** [comment]
This _might_ be an entirely separate issue, but it _might_ not be... I used `fluxcd` to deploy the operator, and flux and the knative-operator (I presume) are constantly rewriting `ClusterRole/knative-serrving-operator-aggregated` (and the corresponding `eventing` cluster role). What's curious is that the `.spec` of these manifests is being rewritten to `null` (by which of `knative-operator` and `kustomize-controller` is hard to tell, but I'm pretty sure `kustomize-controller` is repopulating the manifests).

**Comment by houshengbo** [comment]
Knative operator is now on the release of 1.6.
Min Kubernetes requirement is 1.22.
Plz upgrade your cluster accordingly.
Close this issue for now.

**Comment by Fabian-K** [comment]
I´m facing the same issue running operator 1.8.2 and k8s 1.23.13

```
I0227 16:10:41.259700       1 leaderelection.go:258] successfully acquired lease knative-operator/knative-operator.knative.dev.operator.pkg.reconciler.knativeeventing.reconciler.00-of-01
{"severity":"INFO","timestamp":"2023-02-27T16:10:41.259838436Z","logger":"knative-operator","caller":"leaderelection/context.go:158","message":"\"knative-operator-6fcf68c849-7zk7k_fdbf704e-2bd6-472a-9f78-bb8616db5035\" has started leading \"knative-operator.knative.dev.operator.pkg.reconciler.knativeeventing.reconciler.00-of-01\"","commit":"b339284-dirty","knative.dev/pod":"knative-operator-6fcf68c849-7zk7k"}
I0227 16:10:43.580469       1 leaderelection.go:258] successfully acquired lease knative-operator/knative-operator.knative.dev.operator.pkg.reconciler.knativeserving.reconciler.00-of-01
{"severity":"INFO","timestamp":"2023-02-27T16:10:43.580616994Z","logger":"knative-operator","caller":"leaderelection/context.go:158","message":"\"knative-operator-6fcf68c849-7zk7k_8a209c28-1a04-4b78-8737-6b0ea453a0f3\" has started leading \"knative-operator.knative.dev.operator.pkg.reconciler.knativeserving.reconciler.00-of-01\"","commit":"b339284-dirty","knative.dev/pod":"knative-operator-6fcf68c849-7zk7k"}
{"severity":"INFO","timestamp":"2023-02-27T16:10:43.585615863Z","logger":"knative-operator","caller":"knativeserving/knativeserving.go:81","message":"Deleting cluster-scoped resources","commit":"b339284-dirty","knative.dev/pod":"knative-operator-6fcf68c849-7zk7k","knative.dev/controller":"knative.dev.operator.pkg.reconciler.knativeserving.Reconciler","knative.dev/kind":"operator.knative.dev.KnativeServing","knative.dev/traceid":"cbf2ec3c-000b-4c76-9619-17eaf9e0146d","knative.dev/key":"knative-serving/knative-serving"}
{"severity":"INFO","timestamp":"2023-02-27T16:10:43.673359004Z","logger":"knative-operator","caller":"common/config_maps.go:57","message":"Setting","commit":"b339284-dirty","knative.dev/pod":"knative-operator-6fcf68c849-7zk7k","knative.dev/controller":"knative.dev.operator.pkg.reconciler.knativeserving.Reconciler","knative.dev/kind":"operator.knative.dev.KnativeServing","knative.dev/traceid":"cbf2ec3c-000b-4c76-9619-17eaf9e0146d","knative.dev/key":"knative-serving/knative-serving","map":"config-features","kubernetes.podspec-nodeselector":"enabled"}
{"severity":"INFO","timestamp":"2023-02-27T16:10:43.673433167Z","logger":"knative-operator","caller":"common/config_maps.go:57","message":"Setting","commit":"b339284-dirty","knative.dev/pod":"knative-operator-6fcf68c849-7zk7k","knative.dev/controller":"knative.dev.operator.pkg.reconciler.knativeserving.Reconciler","knative.dev/kind":"operator.knative.dev.KnativeServing","knative.dev/traceid":"cbf2ec3c-000b-4c76-9619-17eaf9e0146d","knative.dev/key":"knative-serving/knative-serving","map":"config-features","kubernetes.podspec-tolerations":"enabled"}
{"severity":"INFO","timestamp":"2023-02-27T16:10:43.673490393Z","logger":"knative-operator","caller":"common/config_maps.go:57","message":"Setting","commit":"b339284-dirty","knative.dev/pod":"knative-operator-6fcf68c849-7zk7k","knative.dev/controller":"knative.dev.operator.pkg.reconciler.knativeserving.Reconciler","knative.dev/kind":"operator.knative.dev.KnativeServing","knative.dev/traceid":"cbf2ec3c-000b-4c76-9619-17eaf9e0146d","knative.dev/key":"knative-serving/knative-serving","map":"config-gc","min-non-active-revisions":"0"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11fd498]

goroutine 427 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GetKind(...)
    k8s.io/apimachinery@v0.25.2/pkg/apis/meta/v1/unstructured/unstructured.go:226
github.com/manifestival/manifestival.okToDelete(0x0)
    github.com/manifestival/manifestival@v0.7.1/manifestival.go:234 +0x38
github.com/manifestival/manifestival.Manifest.delete({{0xc0013f6200, 0x36, 0x40}, {0x1f7d350, 0xc00052f680}, {{0x1f801a8, 0xc00086db90}, 0x0}}, 0x1f7d350?, {0x0, ...})
    github.com/manifestival/manifestival@v0.7.1/manifestival.go:179 +0xae
github.com/manifestival/manifestival.Manifest.Delete({{0xc0013f6200, 0x36, 0x40}, {0x1f7d350, 0xc00052f680}, {{0x1f801a8, 0xc00086db90}, 0x0}}, {0x0, 0x0, ...})
    github.com/manifestival/manifestival@v0.7.1/manifestival.go:116 +0x1e5
knative.dev/operator/pkg/reconciler/common.Uninstall(0xc000b9ddc0)
    knative.dev/operator/pkg/reconciler/common/install.go:77 +0x278
knative.dev/operator/pkg/reconciler/knativeserving.(*Reconciler).FinalizeKind(0xc00053c540, {0x1f7d238, 0xc000c1c7b0}, 0xc00042cea0?)
    knative.dev/operator/pkg/reconciler/knativeserving/knativeserving.go:92 +0x378
knative.dev/operator/pkg/client/injection/reconciler/operator/v1beta1/knativeserving.(*reconcilerImpl).Reconcile(0xc0000ff2c0, {0x1f7d238, 0xc000c1c780}, {0xc000576940, 0x1f})
    knative.dev/operator/pkg/client/injection/reconciler/operator/v1beta1/knativeserving/reconciler.go:240 +0x3fe
knative.dev/pkg/controller.(*Impl).processNextWorkItem(0xc00082c600)
    knative.dev/pkg@v0.0.0-20221014164553-b812affa3893/controller/controller.go:542 +0x58d
knative.dev/pkg/controller.(*Impl).RunContext.func3()
    knative.dev/pkg@v0.0.0-20221014164553-b812affa3893/controller/controller.go:491 +0x68
created by knative.dev/pkg/controller.(*Impl).RunContext
    knative.dev/pkg@v0.0.0-20221014164553-b812affa3893/controller/controller.go:489 +0x312
```
